import { Suspense } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/Navigation'
import Loading from './loading'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rsala',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<p>Loading Navigation...</p>}>
          <Navigation />
        </Suspense>
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
        <Suspense fallback={<p>Loading Navigation...</p>}>
          <Footer />
        </Suspense>
      </body>
    </html>
  )
}
