import { Suspense } from 'react'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/Navigation'
import Loading from './loading'
import Footer from '@/components/Footer'
import { Analytics } from '@vercel/analytics/react'
import Providers from "@/components/Providers";

const inter = Rubik({ subsets: ['arabic'] })

export const metadata: Metadata = {
  title: {
    template: 'Rsala | %s',
    default: 'Rsala', 
  },
  description: 'Generated by create next app',
  keywords: ['Rsala', 'rsala.net', 'majhoul'],

}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Suspense fallback={<p>Loading Navigation...</p>}>
            <Navigation />
          </Suspense>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
          <Suspense fallback={<p>Loading Navigation...</p>}>
            <Footer />
          </Suspense>
          <Analytics />
        </Providers>
      </body>
    </html>
  )
}
